# Outputs:
#   flow.product_responses: Product-specific info an agent needs to provide a quote.
#
triggers:
  - button_id: auto

steps:
  - open_chat

  - (start)
  - ask_form: What is the vehicle's VIN?
    placeholder: ABC123
    quick_replies:
      - text: How do I find my VIN?
        action:
          jump: help_vin
  - flow_set: vehicle_vin

  - flow: flow.salesforce.case.create
    transfer: true
    data:
      product_responses: |-
        Vehicle VIN: (@ flow.vehicle_vin )

  - (help_vin)
  - flow: flow.salesforce.knowledge.search
    jump: search
    data:
      search_query: vin
  - jump: start
