triggers:
  - type: page_open
    when: (@ not thread.page_open )
  - keyword: start

steps:
  - say: Hi! I'm the Acme Insurance assistant. I can help you get an insurance quote
      in just a few clicks!
  - ask: What kind of insurance are you interested in?
    quick_replies:
      - text: Auto insurance
        result: auto
      - text: Commercial insurance
        result: commercial

  - say: No problem.
  - delay: 1
  - say: I'll just need to get some info from you first.
  - delay: 2
  - flow: flow.insurance.(@ flow.result )
