triggers:
  - event_type: meya.salesforce.live_agent.event.session.queue.update
    when: (@ event_user.type.system )

steps:
  - say: You're now in queue position (@ flow.event.data.position | int )
  - if: (@ flow.event.data.position > 0 )
    then:
      flow: flow.salesforce.live_agent.end_chat
      transfer: true
    else: end
